config/routes.rb
EpicookbookAPI::Application.routes.draw do
  namespace :api do
    get '/ingredients/find/:name' => 'ingredients#by_name'
    
    resources :component_ingredients

    resources :ingredients

    resources :components

    post '/ingredients' => 'ingredients#create'
  end

  devise_for :admins

  resources :component_ingredients

  resources :ingredients

  resources :components

  root 'welcome#index'

  get 'add_user' => 'welcome#add_user'

  get 'documentation' => 'welcome#documentation'

  get 'unverified' => 'ingredients#unverified'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :component_ingredients
  has_many :components, through: :component_ingredients

  validates :name, uniqueness: true, presence: true

  def self.delete_component(component_id)
    ingredient_ids = ComponentIngredient.delete_component(component_id)
    ingredient_ids.each do |ii|
      ingredient = Ingredient.find(ii)
      ingredient.components.delete(Component.find(component_id))
      if ingredient.components.length == 0
        ingredient.destroy
      else
        ingredient.update(verified: false)
      end
    end
  end
end

app/controllers/api/ingredients_controller.rb
class Api::IngredientsController < Api::ApiController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: []
  respond_to :json

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def by_name
    @ingredient = Ingredient.where(name: params[:name])[0]
  end


  def new
    @ingredient = Ingredient.new
    components
  end

  def edit
    components
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    add_components_to_ingredients

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { 
          @ingredient.update(verified: false)
          render action: 'show', status: :created, location: @ingredient 
        }
      else
        components
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { 
          @ingredient.update(verified: false)
          head :no_content 
        }
      else
        components
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def unverified
    @ingredients = Ingredient.where(verified: false)
    @components = Component.where(verified: false)
  end

  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def components
    @components ||= Component.all.map {|component| [component.name, component.id]}
  end

  def add_components_to_ingredients
    puts params.inspect
    if params[:ingredient][:components]
      params[:ingredient][:components].each do |component_id|
        next if component_id.to_i == 0
        component = Component.find(component_id.to_i)
        @ingredient.components << component
      end
    end
  end

  
  def ingredient_params
    params.require(:ingredient).permit(:name, :verified, :id, :components => {})
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all.sort {|a, b| 
      if a.verified && b.verified
        a <=> b
      elsif a.verified && !b.verified
        1
      else 
        -1
      end
    }
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  def by_name
    @ingredient = Ingredient.where(name: params[:name])[0]
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    components
  end

  # GET /ingredients/1/edit
  def edit
    components
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @component = Component.new(name: params[:ingredient][:name], basic: false)
    @ingredient.components << @component
    add_components_to_ingredients

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { 
          @ingredient.update(verified: false)
          render action: 'show', status: :created, location: @ingredient 
        }
      else
        components
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update

    respond_to do |format|
      if @ingredient.update(ingredient_params)
        add_components_to_ingredients
        
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { 
          @ingredient.update(verified: false)
          head :no_content 
        }
      else
        components
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def unverified
    @ingredients = Ingredient.where(verified: false)
    @components = Component.where(verified: false)
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def components
      @components ||= Component.all.map {|component| [component.name, component.id]}
    end

    def add_components_to_ingredients
      if params[:ingredient][:components]
        params[:ingredient][:components].each do |component_id|
          next if component_id.to_i == 0
          component = Component.find(component_id.to_i)
          @ingredient.components << component
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :verified, :components => {})
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class='ui checkbox'>
    <% @components.each do |component| %>
      <input type='checkbox' name='ingredient[components][]' value=<%=component[1]%>>
      <label><%= component[0] %>
    <% end %>
  </div>

  <div class='ui checkbox'>
    <%= f.check_box :verified, value: true %>
    <label><strong>Verify?</strong></label>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<div class='ingredient-header'>
  <h1>Ingredients</h1>

  <%= link_to 'New Ingredient', new_ingredient_path %>
</div>

<table class='ingredient-table'>
  <thead>
    <tr>
      <th>Verified?</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td class='verified'><%= ingredient.verified%></td>
        <td class='ingredient-name'><%= link_to ingredient.name, ingredient %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<% if @ingredient.verified %>
  This ingredient has been verified!
<% else %>
  <strong>WARNING:</strong> This ingredient has not been verified!
<% end %>

<p>
  <strong>Components:</strong><br>
  <% @ingredient.components.each do |component| %>
    <%= component.name %><br>
  <% end %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/unverified.html.erb
<h1>Unverified Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Unverified Components</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @components.each do |component| %>
      <tr>
        <td><%= component.name %></td>
        <td><%= link_to 'Show', component %></td>
        <td><%= link_to 'Edit', edit_component_path(component) %></td>
        <td><%= link_to 'Destroy', component, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>