config/routes.rb
EpicookbookAPI::Application.routes.draw do
  namespace :api do
    get '/ingredients/find/:name' => 'ingredients#by_name'
    
    resources :component_ingredients

    resources :ingredients

    resources :components

    post '/ingredients' => 'ingredients#create'
  end

  devise_for :admins

  resources :component_ingredients

  resources :ingredients

  resources :components

  root 'welcome#index'

  get 'add_user' => 'welcome#add_user'

  get 'documentation' => 'welcome#documentation'

  get 'unverified' => 'ingredients#unverified'
end

app/models/component_ingredient.rb
class ComponentIngredient < ActiveRecord::Base
  belongs_to :component 
  belongs_to :ingredient

  def self.delete_component(component_id)
    component_ingredients = ComponentIngredient.where(component_id: component_id)
    ingredient_ids = []
    component_ingredients.each do |ci|
      ingredient_ids << ci.ingredient_id
      ci.destroy
    end
    return ingredient_ids
  end
end

app/controllers/component_ingredients_controller.rb
class ComponentIngredientsController < ApplicationController
  before_action :set_component_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /component_ingredients
  # GET /component_ingredients.json
  def index
    @component_ingredients = ComponentIngredient.all
  end

  # GET /component_ingredients/1
  # GET /component_ingredients/1.json
  def show
  end

  # GET /component_ingredients/new
  def new
    @component_ingredient = ComponentIngredient.new
  end

  # GET /component_ingredients/1/edit
  def edit
  end

  # POST /component_ingredients
  # POST /component_ingredients.json
  def create
    @component_ingredient = ComponentIngredient.new(component_ingredient_params)

    respond_to do |format|
      if @component_ingredient.save
        format.html { redirect_to @component_ingredient, notice: 'Component ingredient was successfully created.' }
        format.json { 
          @component_ingredient.update(verified: false)
          render action: 'show', status: :created, location: @component_ingredient 
        }
      else
        format.html { render action: 'new' }
        format.json { render json: @component_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /component_ingredients/1
  # PATCH/PUT /component_ingredients/1.json
  def update
    respond_to do |format|
      if @component_ingredient.update(component_ingredient_params)
        format.html { redirect_to @component_ingredient, notice: 'Component ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @component_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /component_ingredients/1
  # DELETE /component_ingredients/1.json
  def destroy
    @component_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to component_ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component_ingredient
      @component_ingredient = ComponentIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_ingredient_params
      params.require(:component_ingredient).permit(:component_id, :ingredient_id)
    end
end

app/helpers/component_ingredients_helper.rb
module ComponentIngredientsHelper
end

app/views/component_ingredients/_form.html.erb
<%= form_for(@component_ingredient) do |f| %>
  <% if @component_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@component_ingredient.errors.count, "error") %> prohibited this component_ingredient from being saved:</h2>

      <ul>
      <% @component_ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component_id %><br>
    <%= f.number_field :component_id %>
  </div>
  <div class="field">
    <%= f.label :ingredient_id %><br>
    <%= f.number_field :ingredient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/component_ingredients/edit.html.erb
<h1>Editing component_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @component_ingredient %> |
<%= link_to 'Back', component_ingredients_path %>

app/views/component_ingredients/index.html.erb
<h1>Listing component_ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Component</th>
      <th>Ingredient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @component_ingredients.each do |component_ingredient| %>
      <tr>
        <td><%= component_ingredient.component_id %></td>
        <td><%= component_ingredient.ingredient_id %></td>
        <td><%= link_to 'Show', component_ingredient %></td>
        <td><%= link_to 'Edit', edit_component_ingredient_path(component_ingredient) %></td>
        <td><%= link_to 'Destroy', component_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Component ingredient', new_component_ingredient_path %>

app/views/component_ingredients/new.html.erb
<h1>New component_ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', component_ingredients_path %>

app/views/component_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @component_ingredient.component_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @component_ingredient.ingredient_id %>
</p>

<%= link_to 'Edit', edit_component_ingredient_path(@component_ingredient) %> |
<%= link_to 'Back', component_ingredients_path %>